module.exports = {
  content: ['./app/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  presets: [require("nativewind/preset")],


  theme: {
    extend: {
      colors: {
        background: '#F7F4EF',
        surface: '#EEE9E1',
        'surface-raised': '#FFFFFF',
        ink: '#111008',
        'ink-secondary': '#6B6558',
        'ink-tertiary': '#A89F93',
        'grid-empty': '#DDD8D0',
        'grid-1': '#A8D5B5',
        'grid-2': '#3CCF6E',
        'grid-3': '#1E8A3E',
        'grid-4': '#0D4A21',
        accent: '#E8472A',
        'accent-soft': '#FDE8E4',
        border: '#E0D9CF',
      },
      fontFamily: {
        'inter-black': ['Inter_900Black'],
        'inter-bold': ['Inter_700Bold'],
        'inter-semibold': ['Inter_600SemiBold'],
        'inter-medium': ['Inter_500Medium'],
        'inter-regular': ['Inter_400Regular'],
        'mono': ['SpaceMono_400Regular'],
      },
      fontSize: {
        'display-sm': ['48px', { lineHeight: '52px', letterSpacing: '-1.5px' }],
        'display-lg': ['72px', { lineHeight: '76px', letterSpacing: '-1.5px' }],
        'h1-sm': ['36px', { lineHeight: '40px', letterSpacing: '-1px' }],
        'h1-lg': ['48px', { lineHeight: '52px', letterSpacing: '-1px' }],
        'h2-sm': ['24px', { lineHeight: '28px', letterSpacing: '-0.5px' }],
        'h2-lg': ['28px', { lineHeight: '32px', letterSpacing: '-0.5px' }],
        body: ['15px', { lineHeight: '22px' }],
        'body-lg': ['16px', { lineHeight: '24px' }],
        label: ['13px', { lineHeight: '18px', letterSpacing: '0.5px' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.5px' }],
        caption: ['11px', { lineHeight: '15px', letterSpacing: '0.2px' }],
        wordmark: ['28px', { lineHeight: '32px', letterSpacing: '-1px' }],
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        xxxl: '64px',
      },
      borderRadius: {
        sm: '4px',
        md: '8px',
        lg: '16px',
        xl: '24px',
        full: '9999px',
      },
      boxShadow: {
        card: '0 2px 12px rgba(17, 16, 8, 0.08)',
      },
    },
  },
  plugins: [],
}